%%%-------------------------------------------------------------------
%%% @doc code_lock_inserted - Demonstrates Inserted Events (next_event).
%%%
%%% Uses down/up button events to demonstrate:
%%%   - {next_event, internal, {button, Button}} to convert
%%%     external events into internal events
%%%   - internal event type can only be generated via next_event
%%%   - ?HANDLE_COMMON macro for DRY state delegation
%%%   - state_enter combined with inserted events
%%%
%%% Button model: down(press) -> up(release)
%%% Only the up event (after matching down) triggers a button press.
%%%
%%% @end
%%%-------------------------------------------------------------------
-module(code_lock_inserted).
-behaviour(gen_statem).
-define(NAME, code_lock_inserted).

%% API
-export([start_link/1, down/1, up/1, code_length/0, stop/0, demo/0]).

%% gen_statem callbacks
-export([init/1, callback_mode/0, terminate/3, code_change/4]).
-export([locked/3, open/3]).

%%====================================================================
%% API
%%====================================================================

start_link(Code) ->
    gen_statem:start_link({local, ?NAME}, ?MODULE, Code, []).

down(Button) ->
    gen_statem:cast(?NAME, {down, Button}).

up(Button) ->
    gen_statem:cast(?NAME, {up, Button}).

code_length() ->
    gen_statem:call(?NAME, code_length).

stop() ->
    gen_statem:stop(?NAME).

%%====================================================================
%% gen_statem callbacks
%%====================================================================

init(Code) ->
    process_flag(trap_exit, true),
    Data = #{code => Code, length => length(Code), buttons => []},
    {ok, locked, Data}.

callback_mode() ->
    [state_functions, state_enter].

%% Macro for delegating to handle_common in each state
-define(HANDLE_COMMON,
    ?FUNCTION_NAME(T, C, D) -> handle_common(T, C, D)).

%%--------------------------------------------------------------------
%% Common event handler (shared by all states)
%%--------------------------------------------------------------------

%% down event: record which button is pressed
handle_common(cast, {down, Button}, Data) ->
    {keep_state, Data#{button => Button}};

%% up event: if matches the pressed button, generate internal button event
handle_common(cast, {up, Button}, Data) ->
    case Data of
        #{button := Button} ->
            {keep_state, maps:remove(button, Data),
             [{next_event, internal, {button, Button}}]};
        #{} ->
            keep_state_and_data
    end;

%% Synchronous call: code_length works in any state
handle_common({call, From}, code_length, #{code := Code}) ->
    {keep_state_and_data, [{reply, From, length(Code)}]}.

%%--------------------------------------------------------------------
%% State: locked
%%--------------------------------------------------------------------

locked(enter, _OldState, Data) ->
    do_lock(),
    {keep_state, Data#{buttons := []}};

locked(state_timeout, button, Data) ->
    {keep_state, Data#{buttons := []}};

%% Handle the internal button event (generated by handle_common)
locked(internal, {button, Button},
       #{code := Code, length := Length, buttons := Buttons} = Data) ->
    NewButtons =
        if
            length(Buttons) < Length -> Buttons;
            true -> tl(Buttons)
        end ++ [Button],
    if
        NewButtons =:= Code ->
            {next_state, open, Data};
        true ->
            {keep_state, Data#{buttons := NewButtons},
             [{state_timeout, 30000, button}]}
    end;

?HANDLE_COMMON.

%%--------------------------------------------------------------------
%% State: open
%%--------------------------------------------------------------------

open(enter, _OldState, _Data) ->
    do_unlock(),
    {keep_state_and_data, [{state_timeout, 10000, lock}]};

open(state_timeout, lock, Data) ->
    {next_state, locked, Data};

open(internal, {button, _}, _) ->
    {keep_state_and_data, [postpone]};

?HANDLE_COMMON.

%%====================================================================
%% Internal functions
%%====================================================================

do_lock() ->
    io:format("Locked~n", []).

do_unlock() ->
    io:format("Open~n", []).

terminate(_Reason, State, _Data) ->
    State =/= locked andalso do_lock(),
    ok.

code_change(_OldVsn, State, Data, _Extra) ->
    {ok, State, Data}.

%%====================================================================
%% Demo
%%====================================================================

demo() ->
    io:format("~n=== gen_statem Demo: Inserted Events (down/up) ===~n~n"),

    {ok, Pid} = start_link([a, b, c]),
    io:format("[1] Started code_lock_inserted, pid=~p~n", [Pid]),
    io:format("    Button model: down(press) -> up(release)~n"),
    io:format("    up event generates {next_event, internal, {button, X}}~n~n"),

    %% Press and release buttons
    io:format("--- Pressing buttons (down then up) ---~n"),
    down(a), up(a),
    timer:sleep(50),
    io:format("  down(a) -> up(a) -> internal {button, a}~n"),

    down(b), up(b),
    timer:sleep(50),
    io:format("  down(b) -> up(b) -> internal {button, b}~n"),

    down(c), up(c),
    timer:sleep(50),
    io:format("  down(c) -> up(c) -> internal {button, c} -> Correct!~n~n"),

    %% Query code length (works in open state too)
    Len = code_length(),
    io:format("[2] code_length() = ~p (common handler)~n~n", [Len]),

    stop(),
    timer:sleep(50),
    io:format("[3] Stopped~n"),
    io:format("~n=== Inserted Events Demo Complete ===~n~n"),
    ok.
